name: GitBook Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Get all changed files and use a comma separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: ","

      - name: Generate JSON payload
        id: generate-payload
        run: |
          export PAYLOAD=$(python generate-payload.py ${{ steps.changed-files.outputs.all_changed_files }} ${{ github.sha }})
          echo "Payload: ${PAYLOAD}"
