name: GitBook Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get all changed files and use a comma separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: ","

      - name: Execute Prefect flow
        id: prefect-flow
        run: |
          pip install -U "prefect==2.16.9"
          prefect cloud login -k ${{ secrets.PREFECT_API_KEY }} -w govtexttechgovsg/govtext
          : # execute staging flow run
          prefect deployment run 'update-embeddings/moe-qna' \
            --param changed_files="${{ steps.changed-files.outputs.all_changed_files }}" \
            --param deleted_files="${{ steps.changed-files.outputs.deleted_files }}" \
            --param commit_sha="${{ github.sha }})"
          : # execute production flow run
          prefect deployment run 'update-embeddings/prd-moe-qna' \
            --param changed_files="${{ steps.changed-files.outputs.all_changed_files }}" \
            --param deleted_files="${{ steps.changed-files.outputs.deleted_files }}" \
            --param commit_sha="${{ github.sha }})"
