name: GitBook Workflow

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get all changed files and use a comma separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: ","

      - name: Generate JSON payload
        id: generate-payload
        run: |
          repo_owner="chanckben"
          repo_name="test-target"
          event_type="trigger-workflow"
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          commit_sha="${{ github.sha }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"changed_files\": \"$changed_files\", \"sha\": \"$commit_sha\"}}"
